apiVersion: v1
kind: ServiceAccount
metadata:
  name: polaris
  namespace: cho
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: polaris
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: polaris
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: polaris
subjects:
- kind: ServiceAccount
  name: polaris
  namespace: cho
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polaris-dashboard
  namespace: cho
  labels:
    app: polaris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polaris
  template:
    metadata:
      labels:
        app: polaris
    spec:
      serviceAccountName: polaris
      containers:
      - name: dashboard
        image: quay.io/fairwinds/polaris:8.3
        command: ["polaris", "dashboard", "--port", "8080", "--audit-path", "/tmp/audit.json"]
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: polaris-dashboard
  namespace: cho
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32081
  selector:
    app: polaris

