# /home/cho/argocd/jo/php/regist/myweb-svc-deploy-regist.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-regist-deploy
  namespace: ingress-myweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-regist
  template:
    metadata:
      labels:
        app: php-regist
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 101

      volumes:
        # PHP 코드 ConfigMap
        - name: php-code
          configMap:
            name: regist-php
            defaultMode: 0644
        
        # Nginx 설정 ConfigMap
        - name: regist-nginx-config
          configMap:
            name: nginx-regist-conf
            
      containers:
        # 1. PHP-FPM 컨테이너 (변경 사항 없음)
        - name: php-fpm
          image: eunjun0122/regist:1.1.0
          ports:
            - containerPort: 9000
          securityContext: 
            runAsUser: 0 
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: php-code
              mountPath: /var/www/html/regist
              
        # 2. Nginx 컨테이너
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
            - containerPort: 9000 # ⬅️ 추가: FPM 포트를 Nginx에도 열어 통신 안정성 확보
          securityContext:
            runAsUser: 0
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            # PHP 코드 마운트
            - name: php-code
              mountPath: /var/www/html/regist
              
            # ⭐⭐⭐ 치명적인 마운트 오류 수정: 파일 경로로 정확하게 덮어쓰기 ⭐⭐⭐
            - name: regist-nginx-config
              mountPath: /etc/nginx/conf.d

---
apiVersion: v1
kind: Service
metadata:
  name: php-regist-service
  namespace: ingress-myweb
spec:
  selector:
    app: php-regist
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
