# ----------------------------------------
# php-app-deployment.yaml
# ----------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
  namespace: ingress-myweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      volumes:
        # 1. PHP 코드 ConfigMap 볼륨 (index.php)
        - name: app-code-volume
          configMap:
            name: php-index-file
        # 2. Nginx 설정 ConfigMap 볼륨 (default.conf)
        - name: nginx-config-volume
          configMap:
            name: nginx-config
      containers:
      - name: php-fpm
        image: eunjun0122/myapp:1.0.3
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: app-code-volume
          mountPath: /var/www/html
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-code-volume
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf

---
# ----------------------------------------
# php-service.yaml
# ----------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: ingress-myweb
spec:
  type: ClusterIP
  selector:
    app: php-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80