apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deploy
  namespace: ingress-myweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: login-html
---
apiVersion: v1
kind: Service
metadata:
  name: login-svc
  namespace: ingress-myweb
spec:
  selector:
    app: login
  ports:
  - port: 80
    targetPort: 80
