apiVersion: apps/v1
kind: Deployment
metadata:
  name: edit-deploy
  namespace: ingress-myweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edit
  template:
    metadata:
      labels:
        app: edit
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
         #hpa 리소스 할당
        resources:
          limits:       
            memory: "64Mi"
            cpu: "500m"
          requests:      
            memory: "32Mi"   
            cpu: "250m"       
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: edit-html
---
apiVersion: v1
kind: Service
metadata:
  name: edit-svc
  namespace: ingress-myweb
spec:
  selector:
    app: edit
  ports:
  - port: 80
    targetPort: 80
