# pv 설정
apiVersion: v1
kind: PersistentVolume
metadata:
  name: coconut-pv       # 쿠버네티스에서 관리할 이름
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: coconut-disk  # disk 이름
    fsType: ext4

---
# pvc 설정
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coconut-pvc
  namespace: joo   # kube-prometheus-stack이 설치되는 네임스페이스
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  volumeName: coconut-pv   # pv 이름