# pv 설정
apiVersion: v1
kind: PersistentVolume
metadata:
  name: master-pv       # 쿠버네티스에서 관리할 이름
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: master  # 실제 gcp disk 이름
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.gke.io/zone
          operator: In
          values:
          - asia-northeast3-a 

---
# pvc 설정
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # 변경: StatefulSet의 volumeClaimTemplates에서 생성하는 이름으로 맞춤
  # StatefulSet 템플릿 이름: prometheus-prom-grafana-alertmanager-prometheus-db
  # StatefulSet 이름: prometheus-prom-grafana-alertmanager-prometheus
  # 생성되는 PVC 이름 형식: <volumeClaimTemplate.name>-<statefulset.name>-<ordinal>
  # 아래 이름은 ordinal 0에 해당하는 PVC 명입니다.
  name: prometheus-prom-grafana-alertmanager-prometheus-db-prom-grafana-alertmanager-prometheus-0
  namespace: joo   # kube-prometheus-stack이 설치되는 네임스페이스
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: ""
  volumeName: master-pv   # pv 이름