apiVersion: v1
kind: PersistentVolume
metadata:
  name: coconut-pv       # 쿠버네티스에서 관리할 이름
spec:
  capacity:
    storage: 15Gi        
  accessModes:
    - ReadWriteOnce   
  gcePersistentDisk:
    pdName: coconut-disk  # disk 이름 
    fsType: ext4         
