apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coconut-pvc
  namespace: joo   # kube-prometheus-stack이 설치되는 네임스페이스
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  volumeName: coconut-pv   # pv 이름
