# manual-mariadb-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv-manual
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mariadb"
