apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeview
  namespace: cho
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeview
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeview
subjects:
- kind: ServiceAccount
  name: kubeview
  namespace: cho
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeview
  namespace: cho
  labels:
    app: kubeview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeview
  template:
    metadata:
      labels:
        app: kubeview
    spec:
      serviceAccountName: kubeview
      containers:
      - name: kubeview
        image: ghcr.io/benc-uk/kubeview:0.1.32
        ports:
        - containerPort: 8000
        env:
        - name: IN_CLUSTER
          value: "true"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kubeview
  namespace: cho
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 32083
  selector:
    app: kubeview

