apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-login-deploy
  namespace: ingress-myweb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: php-login
  template:
    metadata:
      labels:
        app: php-login
    spec:
      volumes:
        # PHP 코드 ConfigMap
        - name: php-code
          configMap:
            name: login-php
        # Nginx 설정 ConfigMap
        - name: nginx-config
          configMap:
            name: nginx-config
      containers:
        # 1. PHP-FPM 컨테이너
        - name: php-fpm
          image: eunjun0122/myapp:1.0.4
          ports:
            - containerPort: 9000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"            
          volumeMounts:
            - name: php-code
              mountPath: /var/www/html
        # 2. Nginx 컨테이너
        - name: nginx
          image: nginx:stable-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: php-code
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

---
apiVersion: v1
kind: Service
metadata:
  name: php-login-service
  namespace: ingress-myweb
spec:
  selector:
    app: php-login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
