apiVersion: v1
kind: ServiceAccount
metadata:
  name: skooner-sa
  namespace: cho
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: skooner-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: skooner-sa
  namespace: cho
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skooner
  namespace: cho
  labels:
    k8s-app: skooner
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: skooner
  template:
    metadata:
      labels:
        k8s-app: skooner
    spec:
      serviceAccountName: skooner-sa
      containers:
      - name: skooner
        image: ghcr.io/skooner-k8s/skooner:stable
        ports:
        - containerPort: 4654
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 4654
          initialDelaySeconds: 30
          timeoutSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: skooner
  namespace: cho
  labels:
    k8s-app: skooner
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 4654
    nodePort: 32082
  selector:
    k8s-app: skooner

