apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ops-view
  namespace: cho
  labels:
    application: kube-ops-view
    version: v20.4.0
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-ops-view
  template:
    metadata:
      labels:
        application: kube-ops-view
        version: v20.4.0
    spec:
      containers:
      - name: kube-ops-view
        image: hjacobs/kube-ops-view:20.4.0
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
---
apiVersion: v1
kind: Service
metadata:
  name: kube-ops-view
  namespace: cho
  labels:
    application: kube-ops-view
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    nodePort: 32080
  type: NodePort
  selector:
    application: kube-ops-view
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-ops-view
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  - replicationcontrollers
  - namespaces
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs
  verbs:
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-ops-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-ops-view
subjects:
- kind: ServiceAccount
  name: default
  namespace: cho

