apiVersion: batch/v1
kind: CronJob
metadata:
  name: etcd-backup
  namespace: bae
spec:
  schedule: "*/10 * * * *" # 매일 자정 마다 실행 15시로
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3

  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          hostNetwork: true
          restartPolicy: OnFailure
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"

          containers:
          - name: etcd-backup
            image: registry.k8s.io/etcd:3.5.13-0
            imagePullPolicy: IfNotPresent
            env:
            - name: ETCDCTL_API
              value: "3"
            - name: POD_NAME          
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            command:
            - /bin/sh
            - -c
            - |
              set -e

              SNAPSHOT_FILE="/var/lib/etcd/etcd_backup/etcd-snapshot-${POD_NAME}.db"

              echo "[${POD_NAME}] ${SNAPSHOT_FILE} 스냅샷 생성 시작"

              /usr/local/bin/etcdctl \
                --endpoints=https://127.0.0.1:2379 \
                --cacert=/etc/kubernetes/pki/etcd/ca.crt \
                --cert=/etc/kubernetes/pki/etcd/server.crt \
                --key=/etc/kubernetes/pki/etcd/server.key \
                snapshot save "${SNAPSHOT_FILE}"

              echo "==> 스냅샷 저장 완료, 상태 확인 중..."

              /usr/local/bin/etcdctl \
                --write-out=table \
                snapshot status "${SNAPSHOT_FILE}"

              echo "==> etcd 스냅샷 작업 완료"

              echo "==> Google Drive 업로드 시작"

              rclone copy "${SNAPSHOT_FILE}" \
                google-drive-etcd: \
                --drive-root-folder-id 1C7873kF5fEqB5PfDNfRHaferzm3Gz8aF

              echo "==> Google Drive 업로드 완료"

            volumeMounts:
            - name: etcd-certs
              mountPath: /etc/kubernetes/pki/etcd
              readOnly: true
            - name: etcd-backup-dir
              mountPath: /var/lib/etcd/etcd_backup

          volumes:
          - name: etcd-certs
            hostPath:
              path: /etc/kubernetes/pki/etcd
              type: DirectoryOrCreate
          - name: etcd-backup-dir
            persistentVolumeClaim:
              claimName: etcd-pvc