---
apiVersion: v1
kind: Pod
metadata:
  name: etcd-backup-debug
  namespace: bae
spec:
  hostNetwork: true
  restartPolicy: Never

  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

  containers:
  - name: etcd-backup
    image: registry.k8s.io/etcd:3.5.13-0
    imagePullPolicy: IfNotPresent
    env:
    - name: ETCDCTL_API
      value: "3"
    command:
    - /bin/sh
    - -c
    - |
      set -e

      SNAPSHOT_FILE="/var/lib/etcd/etcd_backup/etcd-snapshot-debug.db"

      echo "[$(date)] ${SNAPSHOT_FILE} 스냅샷 생성 시작 (date 없어도 그냥 통과될 수 있음)"

      /usr/local/bin/etcdctl \
        --endpoints=https://127.0.0.1:2379 \
        --cacert=/etc/kubernetes/pki/etcd/ca.crt \
        --cert=/etc/kubernetes/pki/etcd/server.crt \
        --key=/etc/kubernetes/pki/etcd/server.key \
        snapshot save "${SNAPSHOT_FILE}"

      echo "==> 스냅샷 저장 완료, 상태 확인 중..."

      /usr/local/bin/etcdctl \
        --write-out=table \
        snapshot status "${SNAPSHOT_FILE}"

      echo "==> etcd 스냅샷 작업 완료"

    volumeMounts:
    - name: etcd-certs
      mountPath: /etc/kubernetes/pki/etcd
      readOnly: true
    - name: etcd-backup-dir
      mountPath: /var/lib/etcd/etcd_backup

  volumes:
  - name: etcd-certs
    hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
  - name: etcd-backup-dir
    hostPath:
      path: /var/lib/etcd/etcd_backup
      type: DirectoryOrCreate