---
apiVersion: v1
kind: Pod
metadata:
  name: etcd-backup-debug
  namespace: bae
spec:
  hostNetwork: true
  restartPolicy: Never

  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
  tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

  containers:
  - name: etcd-backup
    image: registry.k8s.io/etcd:3.5.13-0
    imagePullPolicy: IfNotPresent
    env:
    - name: ETCDCTL_API
      value: "3"
    command:
    - /bin/sh
    - -c
    - |
      set -euo pipefail
      set -x  # 디버깅용: 실행되는 명령도 같이 출력

      echo "==> etcd cert 디렉토리 목록"
      ls -l /etc/kubernetes/pki/etcd || echo "etcd cert dir not found"

      etcd_dir=/var/lib/etcd/etcd_backup
      mkdir -p "${etcd_dir}"

      TS=$(date +%Y%m%d%H%M%S)
      SNAPSHOT_FILE="${etcd_dir}/etcd-snapshot-${TS}-debug.db"

      echo "[$(date)] ${SNAPSHOT_FILE} 스냅샷 생성 시작"

      etcdctl \
        --endpoints=https://127.0.0.1:2379 \
        --cacert=/etc/kubernetes/pki/etcd/ca.crt \
        --cert=/etc/kubernetes/pki/etcd/server.crt \
        --key=/etc/kubernetes/pki/etcd/server.key \
        snapshot save "${SNAPSHOT_FILE}"

      echo "==> 스냅샷 저장 완료, 상태 확인 중..."

      etcdctl \
        --write-out=table \
        snapshot status "${SNAPSHOT_FILE}"

      echo "==> etcd 스냅샷 작업 완료"

    volumeMounts:
    - name: etcd-certs
      mountPath: /etc/kubernetes/pki/etcd
      readOnly: true
    - name: etcd-backup-dir
      mountPath: /var/lib/etcd/etcd_backup

  volumes:
  - name: etcd-certs
    hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
  - name: etcd-backup-dir
    hostPath:
      path: /var/lib/etcd/etcd_backup
      type: DirectoryOrCreate
