apiVersion: v1
kind: ServiceAccount
metadata:
  name: headlamp-admin
  namespace: cho
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: headlamp-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: headlamp-admin
  namespace: cho
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  namespace: cho
  labels:
    app: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headlamp
  template:
    metadata:
      labels:
        app: headlamp
    spec:
      serviceAccountName: headlamp-admin
      containers:
      - name: headlamp
        image: ghcr.io/kinvolk/headlamp:latest
        args:
          - "-in-cluster"
          - "-plugins-dir=/headlamp/plugins"
        ports:
        - containerPort: 4466
---
apiVersion: v1
kind: Service
metadata:
  name: headlamp
  namespace: cho
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 4466
    nodePort: 32082
  selector:
    app: headlamp

