apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: nginx-test
spec:
  replicas: 2   # 파드 2개를 띄웁니다 (고가용성 테스트)
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  type: NodePort  # 외부 접속을 위해 NodePort 사용
  selector:
    app: nginx-test
  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30001  # (옵션) 포트를 고정하고 싶으면 주석 해제, 아니면 랜덤 할당