apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-resource-report
  namespace: cho
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-resource-report
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-resource-report
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-resource-report
subjects:
- kind: ServiceAccount
  name: kube-resource-report
  namespace: cho
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-resource-report
  namespace: cho
  labels:
    app: kube-resource-report
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-resource-report
  template:
    metadata:
      labels:
        app: kube-resource-report
    spec:
      serviceAccountName: kube-resource-report
      containers:
      - name: report
        image: hjacobs/kube-resource-report:20.10.0
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kube-resource-report
  namespace: cho
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32083
  selector:
    app: kube-resource-report

