apiVersion: v1
kind: ServiceAccount
metadata:
  name: weave-scope
  namespace: cho
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: weave-scope
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: weave-scope
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: weave-scope
subjects:
- kind: ServiceAccount
  name: weave-scope
  namespace: cho
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: weave-scope-agent
  namespace: cho
  labels:
    name: weave-scope-agent
spec:
  selector:
    matchLabels:
      name: weave-scope-agent
  template:
    metadata:
      labels:
        name: weave-scope-agent
    spec:
      hostNetwork: true
      hostPID: true
      serviceAccountName: weave-scope
      containers:
      - name: agent
        image: weaveworks/scope:1.13.2
        args:
          - "--no-app"
          - "--probe.docker=true"
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: scope-plugins
          mountPath: /var/run/scope/plugins
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: scope-plugins
        hostPath:
          path: /var/run/scope/plugins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weave-scope-app
  namespace: cho
  labels:
    name: weave-scope-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: weave-scope-app
  template:
    metadata:
      labels:
        name: weave-scope-app
    spec:
      serviceAccountName: weave-scope
      containers:
      - name: app
        image: weaveworks/scope:1.13.2
        args:
          - "--no-probe"
        ports:
        - containerPort: 4040
---
apiVersion: v1
kind: Service
metadata:
  name: weave-scope-app
  namespace: cho
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 4040
    nodePort: 32084
  selector:
    name: weave-scope-app

